### ISSUE TITLE
MISO error

### ISSUE THREAD

**Issue by ZeinBader** [nf-core/rnasplice#119]
### Description of the bug

Event ENSG00000005302 not found in pickled directory index. Are you sure this is the right directory for the event?

### Command used and terminal output

```console
WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (2)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (2)` terminated with an error exit status (1)

Command executed:

  sashimi_plot --plot-event ENSG00000005302 index miso_settings.txt --output-dir sashimi
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI":
      python: $(python --version | sed "s/Python //g")
      misopy: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('misopy').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  /usr/local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
    warnings.warn(message, mplDeprecation, stacklevel=1)
  Traceback (most recent call last):
    File "/usr/local/bin/sashimi_plot", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 276, in main
      plot_label=plot_label)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 142, in plot_event
      %(event_name, pickle_dir)
  Exception: Event ENSG00000005302 not found in pickled directory index. Are you sure this is the right directory for the event?

Work dir:
  /flash/SciTechGrp/Zain/54/4ab0250756d10788d62592d4524e58

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

**Comment by jma1991** [comment]
Hey @ZeinBader 

Can you provide the nextflow.log file for me to inspect? The genes provided as default in the nextflow.config are for the human genome, make sure you replace these with gene identifiers found for the reference genome you're using.

**Comment by IanCodes** [comment]
I had the same problem using a yeast genome.  Adding a yeast gene via '--miso_genes' solved the problem.

**Comment by jma1991** [comment]
Closing issue as no response. Please re-open if you are still encountering an issue.
