### ISSUE TITLE
MISO_SASHIMI step fails when using scratch directory

### ISSUE THREAD

**Issue by dkoppstein** [nf-core/rnasplice#74]
### Description of the bug

When using the `process$scratch` variable in the configuration file, NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI fails by looking in the scratch directory instead of where the pickle files actually are. Here, `process$scratch` is set to `$TMPDIR`, which gets expanded to `/local/xxxxx/20738687/cluster_tmp`.

However, then MISO fails with: 

```
Exception: Error: no filename /local/xxxxx/20738687/cluster_tmp/nxf.R4ElqFeq2j/index/chrX/ENSG00000004961.pickle
```

The pickle files are however actually in the output directory, not the scratch directory: 

```
(base) -bash-4.2$ find test2 -name *.pickle | head
test2/misopy/index/chrX/ENSG00000130962.pickle
test2/misopy/index/chrX/ENSG00000126952.pickle
test2/misopy/index/chrX/ENSG00000242013.pickle
test2/misopy/index/chrX/ENSG00000196632.pickle
test2/misopy/index/chrX/ENSG00000130830.pickle
test2/misopy/index/chrX/ENSG00000184033.pickle
test2/misopy/index/chrX/ENSG00000101892.pickle
test2/misopy/index/chrX/ENSG00000133149.pickle
test2/misopy/index/chrX/ENSG00000165194.pickle
test2/misopy/index/chrX/ENSG00000198689.pickle
```

Full error: 

```
-[nf-core/rnasplice] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (1)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (1)` terminated with an error exit status (1)

Command executed:

  sashimi_plot --plot-event ENSG00000004961 index miso_settings.txt --output-dir sashimi

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI":
      python: $(python --version | sed "s/Python //g")
      misopy: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('misopy').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  /usr/local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
    warnings.warn(message, mplDeprecation, stacklevel=1)
  Traceback (most recent call last):
    File "/usr/local/bin/sashimi_plot", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 276, in main
      plot_label=plot_label)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 153, in plot_event
      plot_label=plot_label)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/plot_utils/plot_gene.py", line 675, in plot_density_from_file
      parseGene(pickle_filename, event)
    File "/usr/local/lib/python2.7/site-packages/misopy/parse_gene.py", line 11, in parseGene
      raise Exception, "Error: no filename %s" %(pickle_filename)
  Exception: Error: no filename /local/xxxxx/20738687/cluster_tmp/nxf.R4ElqFeq2j/index/chrX/ENSG00000004961.pickle

```

### Command used and terminal output

```console
nextflow run nf-core/rnasplice -profile test -c dkfz.config --outdir test2 -r dev
```

### Relevant files

# dkfz.config

```
params {
    config_profile_description = 'Deutsches Krebsforschungszentrum (DKFZ) HPC cluster profile provided by nf-core/configs'
    config_profile_contact     = 'Kübra Narcı kuebra.narci@dkfz-heidelberg.de'
    config_profile_name        = 'DKFZ cluster'


    max_cpus   = 30
    max_memory = '250.GB'
    max_time   = '48.h'
}


singularity {
  enabled = true
  autoMounts = true
}

process {
  executor = 'lsf'
  clusterOptions = '-L /bin/bash'
  scratch = '$TMPDIR'
}

executor {
  name = 'lsf'
  perTaskReserve = false
  perJobMemLimit = true
  queueSize = 10
  submitRateLimit = '3 sec'
}

```

### System information

* Nextflow version: 23.04.1 build 5866
* Hardware: HPC (LSF)
* Executor: 'lsf'
* Container engine: Singularity
* OS: CentOS Linux 7
* Version of nf-core/rnasplice: dev

**Comment by dkoppstein** [comment]
I did a bit more digging -- running it with NXF_DEBUG=1 reveals that two different temporary directories from two different LSF jobs are being used. Specifically, the error is 

```
Exception: Error: no filename /local/xxxxx/20769714/nxf.98A1VB7d5I/index/chrX/ENSG00000005302.pickle
```

but the job is being executed in `/local/xxxxx/20769804/nxf.YYBkdvf6cO`:

```
/bin/bash -c cd /local/xxxxx/20769804/nxf.YYBkdvf6cO; eval export PYTHONNOUSERSITE="1" export R_PROFILE_USER="/.Rprofile" export R_ENVIRON_USER="/.Renviron" export JULIA_DEPOT_PATH="/usr/local/share/julia" export PATH="$PATH:/omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/bin"; /bin/bash /omics/odcf/analysis/xxxxx/xxxxx/nextflow/work/33/439d4c44670b38d3bd71734475398f/.command.run nxf_trace
```

I think the specific problem arises because miso somehow hard-encodes the path in the index. Specifically, if I look for the LSF job ID in the `index_gff` working directory, I see that 

```
(base) -bash-4.2$ grep -R 20769714 *
Binary file index/genes_to_filenames.shelve.dat matches
```

so, I suspect that `index_gff` is hard-encoding the absolute path to the filename. It might be necessary to explicitly specify `scratch false` for this step. I will try this now.

**Comment by dkoppstein** [comment]
In my hands, setting `scratch false` in the module seems to make it work (see [here](https://github.com/dkoppstein/rnasplice/commit/a2f9e499a4e5270a7cce85fbb81e0b06c7e7bb73)). However, is it better to do this in the module, or in `conf/modules.config`?
