### ISSUE TITLE
MISO_SASHIMI looks in NXF_HOME subdirectory instead of working directory for output files

### ISSUE THREAD

**Issue by dkoppstein** [nf-core/rnasplice#75]
### Description of the bug

Here, `$NXF_HOME` is set to `/omics/groups/xxxxx/internal/xxxxx/.nextflow`. 

`miso_prefix` gets set to `miso_prefix: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data`. Therefore, it looks for the output file `/omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188383_sorted` which doesn't exist, but the actual location should be in the working directory `test_local`. Actually, the `_sorted` directories are not created there. 

```
(base) -bash-4.2$ ls test_local/misopy/miso_data/
ERR188383  ERR188428  ERR188454  ERR204916
```

Complete error: 

```
 -[nf-core/rnasplice] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (1)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (1)` terminated with an error exit status (1)

Command executed:

  sashimi_plot --plot-event ENSG00000004961 index miso_settings.txt --output-dir sashimi
 
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI":
      python: $(python --version | sed "s/Python //g")
      misopy: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('misopy').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  Reading settings from: miso_settings.txt
  Parsing data:bam_prefix
  Parsing data:miso_prefix
  Parsing data:bam_files
  Parsing data:miso_files
  Parsing plotting:fig_width
  Parsing plotting:fig_height
  Parsing plotting:intron_scale
  Parsing plotting:exon_scale
  Parsing plotting:logged
  Parsing plotting:font_size
  Parsing plotting:ymax
  Parsing plotting:show_posteriors
  Parsing plotting:bar_posteriors
  Parsing plotting:number_junctions
  Parsing plotting:resolution
  Parsing plotting:posterior_bins
  Parsing plotting:gene_posterior_ratio
  Parsing plotting:colors
  Parsing plotting:bar_color
  Parsing plotting:bf_thresholds
  miso_prefix: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188383_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188383_sorted not a directory.
  Error: Could not find MISO output files for sample ERR188383_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188383_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188428_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188428_sorted not a directory.
  Error: Could not find MISO output files for sample ERR188428_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188428_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188454_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188454_sorted not a directory.
  Error: Could not find MISO output files for sample ERR188454_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188454_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR204916_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR204916_sorted not a directory.
  Error: Could not find MISO output files for sample ERR204916_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR204916_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Reading dimensions from settings...
   - Height: 7.00
   - Width: 7.00
  Plotting read densities and MISO estimates along event...
    - Event: ENSG00000004961
  Setting up plot using dimensions:  [7.0, 7.0]
  Using intron scale  30.0
  Using exon scale  4.0
  Reading sample label: ERR188383_sorted.bam
  Processing BAM: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/star/ERR188383_sorted.bam

Command error:
  Parsing plotting:number_junctions
  Parsing plotting:resolution
  Parsing plotting:posterior_bins
  Parsing plotting:gene_posterior_ratio
  Parsing plotting:colors
  Parsing plotting:bar_color
  Parsing plotting:bf_thresholds
  miso_prefix: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188383_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188383_sorted not a directory.
  Error: Could not find MISO output files for sample ERR188383_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188383_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188428_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188428_sorted not a directory.
  Error: Could not find MISO output files for sample ERR188428_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188428_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188454_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188454_sorted not a directory.
  Error: Could not find MISO output files for sample ERR188454_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR188454_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Searching for MISO files in: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR204916_sorted
    - Looking for chromosome X directories
  Error: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR204916_sorted not a directory.
  Error: Could not find MISO output files for sample ERR204916_sorted (after searching in /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/misopy/miso_data/ERR204916_sorted and its subdirectories). Are you sure MISO output files are present in that directory?
  Reading dimensions from settings...
   - Height: 7.00
   - Width: 7.00
  Plotting read densities and MISO estimates along event...
    - Event: ENSG00000004961
  Setting up plot using dimensions:  [7.0, 7.0]
  Using intron scale  30.0
  Using exon scale  4.0
  Reading sample label: ERR188383_sorted.bam
  Processing BAM: /omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/star/ERR188383_sorted.bam
  Traceback (most recent call last):
    File "/usr/local/bin/sashimi_plot", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 276, in main
      plot_label=plot_label)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 153, in plot_event
      plot_label=plot_label)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/plot_utils/plot_gene.py", line 698, in plot_density_from_file
      plot_title=plot_title)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/plot_utils/plot_gene.py", line 260, in plot_density
      junction_log_base=junction_log_base)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/plot_utils/plot_gene.py", line 48, in plot_density_single
      bamfile = pysam.Samfile(bam_filename, 'rb')
    File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
    File "pysam/libcalignmentfile.pyx", line 950, in pysam.libcalignmentfile.AlignmentFile._open
  IOError: [Errno 2] could not open alignment file `/omics/groups/xxxxx/internal/xxxxx/.nextflow/assets/nf-core/rnasplice/test_local/star/ERR188383_sorted.bam`: No such file or directory

Work dir:
  /omics/odcf/analysis/xxxxx_projects/sb_tall_lines/nextflow/work/99/c923adb950181d6c7810fcdf94cecc

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details


```

### Command used and terminal output

```console
nextflow run nf-core/rnasplice -profile test -c local.config --outdir test_local -r dev
```

### Relevant files

# local.config

```
params {
    config_profile_description = 'Deutsches Krebsforschungszentrum (DKFZ) HPC cluster profile provided by nf-core/configs'
    config_profile_contact     = 'Kübra Narcı kuebra.narci@dkfz-heidelberg.de'
    config_profile_name        = 'DKFZ cluster'


    max_cpus   = 16
    max_memory = '48.GB'
    max_time   = '48.h'
}


singularity {
  enabled = true
  autoMounts = true
}

process {
  executor = 'local'
}

executor {
  name = 'local'
  cpus = 16
  memory = '48 GB'
}
```

### System information

* Nextflow version: 23.04.1 build 5866
* Hardware: LSF HPC
* Executor: 'local'
* Container engine: Singularity
* OS: CentOS 7 Linux
* Version of nf-core/rnasplice: dev

**Comment by bensouthgate** [comment]
Hi @dkoppstein I believe this might be an issue with how the `--bam_prefix` and `--miso_prefix` are defined within the `modules.config` file. I think this will need to be refactored to work on all setups. @valentinoruggieri something like `stageInMode = 'copy'` might work if the normal stage in approach is not working for MISO.

**Comment by dkoppstein** [comment]
Not sure if it's the universal solution, but changing `${projectDir}` to `${launchDir}` as [here](https://github.com/dkoppstein/rnasplice/commit/9ce56cf35caed3d3e609f1f37dd8996c506e2af2) seems to make it run for me.

**Comment by dkoppstein** [comment]
I have [committed fixes on my fork](https://github.com/nf-core/rnasplice/compare/dev...dkoppstein:rnasplice:dev) for this issue and #74, but don't have access to a linux box where I can run the docker version of the test at the moment (only Singularity). Could I ask one of the devs to run the formal docker test, then I could create the PR?

**Comment by valentinoruggieri** [comment]
@dkoppstein , thank you for your revisions. We tested your fork on docker but we are still getting some problems. 
Since the issue only happens when running the pipe using URL, for a temporary solution you can download/clone the pipe and run it (nextflow run main.nf ...) 
Keep you updated
